// Build the Stage 3 review client into a single IIFE the Python renderer embeds.
//
// This is build-time tooling only. The compiled bundle is committed under
// src/osm_scenario/assets/, so an installed CLI never needs Node.
import { build, context } from "esbuild";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(here, "../src/osm_scenario/assets/review-client.js");

mkdirSync(dirname(outfile), { recursive: true });

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/main.ts")],
  outfile,
  bundle: true,
  format: "iife",
  target: ["es2022"],
  platform: "browser",
  // CSS travels as a string the client injects, so the HTML stays one file.
  loader: { ".css": "text" },
  minify: true,
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: "/* Generated by web/build.mjs. Do not edit by hand; edit web/src and rebuild. */",
  },
};

if (process.argv.includes("--watch")) {
  const ctx = await context(options);
  await ctx.watch();
  process.stdout.write(`watching -> ${outfile}\n`);
} else {
  await build(options);
  process.stdout.write(`built -> ${outfile}\n`);
}
