// Build the Stage 3 review client into a single IIFE the Python renderer embeds.
//
// This is build-time tooling only. The compiled bundle is committed under
// src/osm_scenario/assets/, so an installed CLI never needs Node.
import { build, context } from "esbuild";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, "../src/osm_scenario/assets");
const outfile = resolve(assets, "review-client.js");

mkdirSync(assets, { recursive: true });

/** Shared by both clients. Separate bundles rather than one: the Stage 3 reviewer and the
 * Stage 6 route builder share no code, and a page should not carry the other's.
 *
 * @param {string} entry
 * @param {string} out
 * @returns {import("esbuild").BuildOptions}
 */
const optionsFor = (entry, out) => ({
  entryPoints: [resolve(here, entry)],
  outfile: out,
  bundle: true,
  format: "iife",
  target: ["es2022"],
  platform: "browser",
  // CSS travels as a string the client injects, so the HTML stays one file.
  loader: { ".css": "text" },
  minify: true,
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: "/* Generated by web/build.mjs. Do not edit by hand; edit web/src and rebuild. */",
  },
});

const bundles = [
  optionsFor("src/main.ts", outfile),
  optionsFor("src/route/main.ts", resolve(assets, "route-client.js")),
];

if (process.argv.includes("--watch")) {
  for (const options of bundles) {
    const ctx = await context(options);
    await ctx.watch();
    process.stdout.write(`watching -> ${options.outfile}\n`);
  }
} else {
  for (const options of bundles) {
    await build(options);
    process.stdout.write(`built -> ${options.outfile}\n`);
  }
}
